version: '3.0'

services:

  nginx:
    container_name: learning_nginx
    image: 'nginx:latest'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
      - mysql
      - redis
    restart: always
    networks:
      - learning
  php:
    build:
      context: .
      dockerfile: DockerFile
    #    image: 'php:8.2-fpm'
    volumes:
      - .:/var/www/html
    container_name: learning_php
    environment:
      - XDEBUG_SESSION=1
      - PHP_IDE_CONFIG=serverName=learning
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - learning

  mysql:
    platform: linux/x86_64
    container_name: learning_mysql
    image: 'mysql:5.7'
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    networks:
      - learning

  redis:
    platform: linux/x86_64
    container_name: learning_redis
    image: 'redis:latest'
    restart: always
    networks:
      - learning

networks:
  learning:
