version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9003:9003"
    volumes:
      - .:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t public
